export type GameStageKey =
  | "earlyGame"
  | "earlyMidGame"
  | "lateMidGame"
  | "lateGame"
  | "moreLateGame"
  | "veryLateGame"
  | "binaryViking";

export type Tier = "S++" | "S+" | "A" | "B" | "C" | "F";

export const GAME_STAGES: { value: GameStageKey; label: string }[] = [
  { value: "earlyGame", label: "Early Game (<22 Arcana)" },
  { value: "earlyMidGame", label: "Early Mid Game (before ach408)" },
  { value: "lateMidGame", label: "Late Mid Game (before ach420)" },
  { value: "lateGame", label: "Late Game (after ach420)" },
  { value: "moreLateGame", label: "More Late Game (>1M CL)" },
  { value: "veryLateGame", label: "Very late game (>1e9 CL)" },
  { value: "binaryViking", label: "B1naryV1k1ng" },
];

export interface TarotCooldownCard {
  index: number;
  name: string;
  imageKey: string;
  romanNumber: string;
  hours: number;
  minutes: number;
  seconds: number;
  tiers: Record<GameStageKey, Tier>;
}

export const TAROT_COOLDOWN_CARDS: TarotCooldownCard[] = [
  {
    index: 0,
    name: "The Fool",
    imageKey: "the_fool",
    romanNumber: "0",
    hours: 0,
    minutes: 0,
    seconds: 53,
    tiers: {
      earlyGame: "S+",
      earlyMidGame: "S+",
      lateMidGame: "S+",
      lateGame: "S+",
      moreLateGame: "S+",
      veryLateGame: "S++",
      binaryViking: "S++",
    },
  },
  {
    index: 1,
    name: "The Magician",
    imageKey: "the_magician",
    romanNumber: "I",
    hours: 0,
    minutes: 15,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "C",
      binaryViking: "F",
    },
  },
  {
    index: 2,
    name: "The High Priestess",
    imageKey: "the_high_priestess",
    romanNumber: "II",
    hours: 0,
    minutes: 22,
    seconds: 30,
    tiers: {
      earlyGame: "S+",
      earlyMidGame: "A",
      lateMidGame: "A",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 3,
    name: "The Empress",
    imageKey: "the_empress",
    romanNumber: "III",
    hours: 0,
    minutes: 35,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 4,
    name: "The Emperor",
    imageKey: "the_emperor",
    romanNumber: "IV",
    hours: 0,
    minutes: 45,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "C",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 5,
    name: "The Hierophant",
    imageKey: "the_hierophant",
    romanNumber: "V",
    hours: 1,
    minutes: 50,
    seconds: 27,
    tiers: {
      earlyGame: "S+",
      earlyMidGame: "S+",
      lateMidGame: "A",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 6,
    name: "The Lovers",
    imageKey: "the_lovers",
    romanNumber: "VI",
    hours: 0,
    minutes: 55,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 7,
    name: "The Chariot",
    imageKey: "chariot",
    romanNumber: "VII",
    hours: 1,
    minutes: 8,
    seconds: 30,
    tiers: {
      earlyGame: "S++",
      earlyMidGame: "S++",
      lateMidGame: "S++",
      lateGame: "S++",
      moreLateGame: "S++",
      veryLateGame: "A",
      binaryViking: "F",
    },
  },
  {
    index: 8,
    name: "Strength",
    imageKey: "the_strength",
    romanNumber: "VIII",
    hours: 0,
    minutes: 40,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 9,
    name: "The Hermit",
    imageKey: "the_hermit",
    romanNumber: "IX",
    hours: 1,
    minutes: 5,
    seconds: 0,
    tiers: {
      earlyGame: "S+",
      earlyMidGame: "A",
      lateMidGame: "A",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 10,
    name: "Wheel of Fortune",
    imageKey: "wheel_of_fortune",
    romanNumber: "X",
    hours: 0,
    minutes: 30,
    seconds: 0,
    tiers: {
      earlyGame: "F",
      earlyMidGame: "F",
      lateMidGame: "F",
      lateGame: "F",
      moreLateGame: "F",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 11,
    name: "Justice",
    imageKey: "justice",
    romanNumber: "XI",
    hours: 0,
    minutes: 48,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 12,
    name: "The Hanged Man",
    imageKey: "the_hanged_man",
    romanNumber: "XII",
    hours: 1,
    minutes: 12,
    seconds: 0,
    tiers: {
      earlyGame: "S+",
      earlyMidGame: "A",
      lateMidGame: "A",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 13,
    name: "Death",
    imageKey: "death",
    romanNumber: "XIII",
    hours: 0,
    minutes: 52,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "A",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 14,
    name: "Temperance",
    imageKey: "temperance",
    romanNumber: "XIV",
    hours: 0,
    minutes: 38,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 15,
    name: "The Devil",
    imageKey: "the_devil",
    romanNumber: "XV",
    hours: 1,
    minutes: 25,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 16,
    name: "The Tower",
    imageKey: "the_tower",
    romanNumber: "XVI",
    hours: 0,
    minutes: 42,
    seconds: 0,
    tiers: {
      earlyGame: "S+",
      earlyMidGame: "A",
      lateMidGame: "A",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 17,
    name: "The Star",
    imageKey: "the_star",
    romanNumber: "XVII",
    hours: 0,
    minutes: 58,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 18,
    name: "The Moon",
    imageKey: "the_moon",
    romanNumber: "XVIII",
    hours: 1,
    minutes: 18,
    seconds: 0,
    tiers: {
      earlyGame: "A",
      earlyMidGame: "A",
      lateMidGame: "B",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 19,
    name: "The Sun",
    imageKey: "the_sun",
    romanNumber: "XIX",
    hours: 0,
    minutes: 28,
    seconds: 0,
    tiers: {
      earlyGame: "S+",
      earlyMidGame: "S+",
      lateMidGame: "A",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 20,
    name: "Judgement",
    imageKey: "judgement",
    romanNumber: "XX",
    hours: 1,
    minutes: 32,
    seconds: 0,
    tiers: {
      earlyGame: "S+",
      earlyMidGame: "A",
      lateMidGame: "A",
      lateGame: "B",
      moreLateGame: "C",
      veryLateGame: "F",
      binaryViking: "F",
    },
  },
  {
    index: 21,
    name: "The World",
    imageKey: "the_world",
    romanNumber: "XXI",
    hours: 1,
    minutes: 45,
    seconds: 0,
    tiers: {
      earlyGame: "S++",
      earlyMidGame: "S++",
      lateMidGame: "S+",
      lateGame: "A",
      moreLateGame: "B",
      veryLateGame: "C",
      binaryViking: "F",
    },
  },
];

export function formatCooldown(h: number, m: number, s: number): string {
  const pad = (n: number) => n.toString().padStart(2, "0");
  return `${h}:${pad(m)}:${pad(s)}`;
}

export function cooldownToSeconds(
  hours: number,
  minutes: number,
  seconds: number,
): number {
  return hours * 3600 + minutes * 60 + seconds;
}
